# Generated by Django 5.2.7 on 2025-10-06 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licence_number',
            new_name='license_number',
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(default=uuid.UUID('86117972-642e-42fb-8a77-8d272d346aa9'), primary_key=True, serialize=False),
        ),
    ]
